# Generated by Django 6.0.2 on 2026-03-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('OTP_REQUESTED', 'OTP Requested'), ('OTP_VERIFIED', 'OTP Verified'), ('OTP_FAILED', 'OTP Failed'), ('OTP_LOCKED', 'OTP locked')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['email', '-created_at'], name='audit_audit_email_e25057_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'),
        ),
    ]
